# Generated by Django 4.0.4 on 2022-05-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_blog_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cuerpo',
            field=models.CharField(max_length=250),
        ),
    ]
